// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NwsOffice struct {
	ID    string
	City  pgtype.Text
	State pgtype.Text
}

type Report struct {
	ID                  pgtype.UUID
	RptType             interface{}
	ReportedTime        pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	VarCol              pgtype.Int4
	DistFromLocation    int32
	HeadingFromLocation string
	County              string
	State               pgtype.Text
	Latitude            pgtype.Text
	Longitude           pgtype.Text
	EventLocation       interface{}
	Comments            pgtype.Text
	NwsOffice           pgtype.Text
	Location            string
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type SpatialRefSy struct {
	Srid      int32
	AuthName  pgtype.Text
	AuthSrid  pgtype.Int4
	Srtext    pgtype.Text
	Proj4text pgtype.Text
}

type XrefReportTypeVarCol struct {
	RptType       interface{}
	ColumnHeading string
}
